repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-toml
      - id: check-yaml
        args: [--allow-multiple-documents]

  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.6
    hooks:
      - id: codespell
        exclude: README.md

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.10
    hooks:
      - id: ruff-format
        name: ruff-format
        entry: poetry run ruff format app tests
        language: system
        types: [python]
        require_serial: true
        pass_filenames: false

      - id: ruff-check
        name: ruff-check
        entry: poetry run ruff check --fix app tests
        language: system
        types: [python]
        pass_filenames: false

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
      - id: mypy
        name: mypy
        entry: poetry run mypy . --config-file ./pyproject.toml --namespace-packages
        language: system
        types: [python]
        pass_filenames: false
